repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        name: check YAML
      - id: check-json
        name: check JSON
      - id: trailing-whitespace
        exclude: ^README.md$
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        entry: bash -c 'isort "$@"; git add -u' --

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        entry: bash -c 'black "$@"; git add -u' --

  - repo: local
    hooks:
      - id: run-tests
        name: Launch tests using pytest before push
        entry: bash -c "PYTHONPATH=. poetry run pytest"
        language: system
        pass_filenames: false
        stages: [ pre-push ]